config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 10 }
    validates :description, presence: true, length: {minimum: 10, maximum: 50}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:update, :destroy, :edit, :show]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:success] = "article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end
    
    def edit
        #@article = Article.find(params[:id]) 
    end
    
    def update
        #@article = Article.find(params[:id])
        
        if @article.update(article_params)
            flash[:notice] = "Article was successfukky updated"
            redirect_to article_path(@article)
        else
            render :edit
        end
    end
    
    def show
        #@article = Article.find(params[:id])    
    end
    
    def destroy
       #@article = Article.find(params[:id]) 
       @article.destroy
       redirect_to articles_path
    end
    
    private
    def set_article
       @article = Article.find(params[:id]) 
    end
    
    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        
    end
    
    def about
    
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the alpha blog #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "User updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    
    end
    
    def show
        @user = User.find(params[:id])
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for( user ,option = {size: 80} )
        if user.email
            gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
            size = option[:size]
            gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
            image_tag(gravatar_url, alt: user.username, class: "img-circle")
        end
    end
    
end

app/views/articles/_article.html.erb
 <% listObj.each do |article| %>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="panel-title"><%= article.title %></h2>
        </div>
        <div class="panel-body">
            <%= article.description %>
            <hr>
            <div class="container article_details">
                <small>
                    created_by: <%= article.user.username if article.user %>,
                    created <%= time_ago_in_words(article.created_at) %> ago, 
                    last update <%= time_ago_in_words(article.updated_at) %> ago.
                </small>
            </div>
            <div align="right">
                <%= link_to "Show", article_path(article), class: "btn btn-success" %> ||
                <%= link_to " Edit", edit_article_path(article),class: "btn btn-primary glyphicon glyphicon-edit" %> ||
                <%= link_to "", article_path(article), method: :Delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger glyphicon glyphicon-trash"%>
            </div>
        </div>
    </div>
    <% end %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>The following errors prevented the article from getting created</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>


<div class="row">
    
    <%=  form_for @article do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <div >
        <%= f.text_field :title, class: "form-control", id: "exampleInputTitle1", placeholder: "Title" %>
        </div>
    </div>
        
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10, class: "form-control", id: "exampleInputDescription1", placeholder: "Description" %>
    </div>
    
    <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
    </div>
</div>
    <%end%>
<div class="col-sm-6 col-sm-offsit-4 cancle", align="center">
    <%= link_to " Cancle", articles_path, class: "btn btn-primary glyphicon glyphicon-remove" %>
</div>

app/views/articles/edit.html.erb
<h1 align="center"> Edit articles</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class = "container">
    <div class ="row">
        <div class= "col col-sm-8 col-sm-offset-0">
            <div class="container well center">
                <h1 align="center"> Articles Listing</h1>
                <%= link_to " New", new_article_path, class: "btn btn-primary glyphicon glyphicon-plus" %>
            </div>
        </div>
    </div>
    
    <%= render 'article', listObj: @articles %>
    <div>
        <%= will_paginate %>
    </div>
</div>

app/views/articles/new.html.erb
<h1 align="center">create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> <%= @article.title %>  </h2>
    

<div class="well center">
    <ul class="listing">
        <div class= "row">
            <div class = "col-md-4 col-md-offset-4">
                <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                <li><%= link_to @article.user.username, user_path(@article.user) %></li>
                <li><small> <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %> </small></li>
            </div>
        </div>
    </ul>
    <h3 class="center"> Description </h3>
    <hr>
    <%= simple_format(@article.description) %> 
    <hr>
    <%= link_to "Articles", articles_path, class: "btn btn-success" %> ||
    <%= link_to " Edit", edit_article_path(@article), class: "btn btn-primary glyphicon glyphicon-edit" %> ||
    <%= link_to "", article_path(@article), method: :delete, data: {confirm: "Are you sure?"},class: "btn btn-danger glyphicon glyphicon-trash" %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            copyright &copy <a href="https://www.udemy.com" target="_blank">the complete ruby on rails developer course</a> by <a href="https://www.mashrurhossain.com/" target="_blank">Mashrur Hossain</a>
        </small>
        <ul>
            <li> <%= link_to "About", about_path %> </li>
        </ul>
    </footer>
</div>

app/views/layouts/_navigationbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha-blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Articles", articles_path,class: "active", id: "articles" %> </li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li> <%= link_to "new Article", new_article_path %>  </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "About", about_path %>  </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alpha-blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="background">
  <%= render "layouts/navigationbar" %>
  
  <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
  <div class="container">
    <%= yield %>  
  </div>
  <%= render "layouts/footer" %>

</body>
</html>

app/views/pages/about.html.erb
<h1> About </h1>

<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>ALPHA-BLOG</h1>
    <p><%= link_to "Sign up", "#",class:"btn btn-primary btn-lg signup-btn" %></p>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <h2>The following errors prevented the article from getting created</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>


<div class="row">
    
    <%=  form_for @user do |f| %>
    <div class="form-group">
        <%= f.label :username %>
        <div >
        <%= f.text_field :username, class: "form-control", id: "exampleInputTitle1", placeholder: "Enter User name" %>
        </div>
    </div>
        
    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", id: "exampleInputDescription1", placeholder: "Enter Email" %>
    </div>
    
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", id: "exampleInputDescription1", placeholder: "Enter password" %>
    </div>
    
    <div class="form-group">
        <%= f.submit(@user.new_record? ? "SignUp" : "update user", class: "btn btn-primary") %>
    </div>
</div>
    <%end%>
<div class="col-sm-6 col-sm-offsit-4 cancle", align="center">
    <%= link_to " Cancle", articles_path, class: "btn btn-primary glyphicon glyphicon-remove" %>
</div>

app/views/users/edit.html.erb
<h1 align="center"> Edit user </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align= "center"> Users </h1>
<% @users.each do |user| %>
    <ul class="listing center">
        <div class= "row">
            <div class = "well col-md-4 col-md-offset-4">
                <li><%= link_to gravatar_for(user), user_path(user) %></li>
                <li><%= link_to user.username, user_path(user) %></li>
                <li><small> <%= pluralize(user.articles.count, "article") if user.articles %> </small></li>
            </div>
        </div>
    </ul>
<% end %>
<div>
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center" > Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s profile </h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user , size: 150 %>
    </div>
</div>

<h4 align="center"> <%= @user.username %>'s articles </h4>
<%= render 'articles/article', listObj: @user_articles %>
<div>
    <%= will_paginate @user_articles %>
</div>